name: navigation_and_routing
description: Navigation and routing sample app
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: 3.7.7

dependencies:
  adaptive_navigation: ^0.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  path_to_regexp: ^0.4.0
  quiver: ^3.1.0
  url_launcher: ^6.1.1
  url_strategy: ^0.2.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  test: ^1.16.0

flutter:
  uses-material-design: true